services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: copilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - copilot-postgres:/var/lib/postgresql/data

volumes:
  copilot-postgres:
